// SPDX-FileCopyrightText: 2026 Dr Marcus Baw
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Generate the TypeScript IPC contract from the Rust boundary types.
//!
//! @see spec/400-gui/spec.md
//! @see spec/400-gui/design.md [DES-BOUNDARY]

use std::path::PathBuf;

use cortex_gui::{DashboardSnapshot, ParameterView};
use cortex_rs::ParameterInput;
use cortex_rs::nano::{NanoAmpControl, NanoBypassTarget, NanoFxParameter, NanoFxSlot};
use ts_rs::{Config, TS};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let output = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/shared/ipc/generated");

    if output.exists() {
        std::fs::remove_dir_all(&output)?;
    }
    std::fs::create_dir_all(&output)?;

    let config = Config::new().with_out_dir(&output);
    DashboardSnapshot::export_all(&config)?;
    ParameterView::export_all(&config)?;
    ParameterInput::export_all(&config)?;
    NanoAmpControl::export_all(&config)?;
    NanoBypassTarget::export_all(&config)?;
    NanoFxParameter::export_all(&config)?;
    NanoFxSlot::export_all(&config)?;

    let mut bindings = Vec::new();
    for entry in std::fs::read_dir(&output)? {
        let path = entry?.path();
        if path.extension().is_some_and(|extension| extension == "ts") {
            let Some(binding) = path.file_stem().and_then(|stem| stem.to_str()) else {
                return Err("generated binding filename is not valid UTF-8".into());
            };
            bindings.push(binding.to_owned());

            let source = std::fs::read_to_string(&path)?;
            let mut normalized = source
                .lines()
                .map(str::trim_end)
                .collect::<Vec<_>>()
                .join("\n");
            normalized.push('\n');
            std::fs::write(path, normalized)?;
        }
    }
    bindings.sort_unstable();

    let mut index = String::from(
        "// This file was generated by cortex-gui's TypeScript binding generator. Do not edit this file manually.\n",
    );
    for binding in bindings {
        index.push_str(&format!(
            "export type {{ {binding} }} from \"./{binding}\";\n"
        ));
    }
    std::fs::write(output.join("index.ts"), index)?;

    Ok(())
}
