# SPDX-FileCopyrightText: 2026 Dr Marcus Baw
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "cortex-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = "2.6.3"

[dependencies]
serde = { workspace = true, features = ["derive"] }
tauri = "2.11.5"
cortex-rs = { path = "../../crates/cortex-rs", default-features = false }
